In [27]:
import numpy as np

insert

In [28]:
arr = np.array([1,2,3,4])
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [29]:
x = np.insert(arr, 2 , 40)
x

array([ 1,  2, 40,  3,  4])

In [30]:
x = np.insert(arr, (2,4) , 40.7)
x

array([ 1,  2, 40,  3,  4, 40])

In [31]:
arr = np.array([[1,2,3],[1,2,3]])

x = np.insert(arr, 2, 22 ,axis=0)
x

array([[ 1,  2,  3],
       [ 1,  2,  3],
       [22, 22, 22]])

In [32]:
x = np.insert(arr, 2, [22,23,24] ,axis=0)
x

array([[ 1,  2,  3],
       [ 1,  2,  3],
       [22, 23, 24]])

In [33]:
x = np.insert(arr, 2, 22 ,axis=1)
x

array([[ 1,  2, 22,  3],
       [ 1,  2, 22,  3]])

In [34]:
x = np.append(arr,[6.5,9,10])
x

array([ 1. ,  2. ,  3. ,  1. ,  2. ,  3. ,  6.5,  9. , 10. ])

delete

In [38]:
arr = np.array([1,2,3,4])

x = np.delete(arr,2)
x

array([1, 2, 4])