In [75]:
import numpy as np

Arithmetic operations

In [76]:
ar1 = np.array([1,2,3,4,5])

varAdd1 = ar1 + 3
print(varAdd1)

ar2 = np.array([1,2,3,4,2])
varAdd2 = ar1 + ar2
varAdd2

[4 5 6 7 8]


array([2, 4, 6, 8, 7])

In [77]:
sub = ar1 - ar2
sub

array([0, 0, 0, 0, 3])

In [78]:
mul = ar1 * ar2
mul

array([ 1,  4,  9, 16, 10])

In [79]:
div = ar1 / ar2
div

array([1. , 1. , 1. , 1. , 2.5])

In [80]:
mod = ar1 % ar2
mod

array([0, 0, 0, 0, 1])

In [81]:
print(np.add(ar1,ar2))
print(np.subtract(ar1,ar2))
print(np.multiply(ar1,ar2))
print(np.divide(ar1,ar2))
print(np.mod(ar1,ar2))
print(np.power(ar1,ar2))
print(ar1)
print(np.reciprocal(ar1))

[2 4 6 8 7]
[0 0 0 0 3]
[ 1  4  9 16 10]
[1.  1.  1.  1.  2.5]
[0 0 0 0 1]
[  1   4  27 256  25]
[1 2 3 4 5]
[1 0 0 0 0]


In [85]:
ar1 = np.array([[1,2,3,4],[1,2,3,4]])
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar1)
print(ar2)

print(np.add(ar1,ar2))
print(np.subtract(ar1,ar2))
print(np.multiply(ar1,ar2))
print(np.divide(ar1,ar2))
print(np.mod(ar1,ar2))
print(np.power(ar1,ar2))
print(np.reciprocal(ar1))

[[1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]]
[[2 4 6 8]
 [2 4 6 8]]
[[0 0 0 0]
 [0 0 0 0]]
[[ 1  4  9 16]
 [ 1  4  9 16]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0 0 0 0]
 [0 0 0 0]]
[[  1   4  27 256]
 [  1   4  27 256]]
[[1 0 0 0]
 [1 0 0 0]]
