In [23]:
import numpy as np

indexing

In [24]:
ar = np.array([1,2,3,4])

print(ar[0])
print(ar[-1])

for i in range(-4,4):
    print("arr",i,"=",ar[i])

1
4
arr -4 = 1
arr -3 = 2
arr -2 = 3
arr -1 = 4
arr 0 = 1
arr 1 = 2
arr 2 = 3
arr 3 = 4


In [25]:
ar = np.array([[[1,2,3],[1,2,3]],[[4,5,6],[4,5,6]],[[7,8,9],[7,8,9]]])
print(ar)
print(ar.shape)

for i in range(3):
    for j in range(2):
        for k in range(3):
            print("arr",i,j,k,"=",ar[i,j,k])

[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]]]
(3, 2, 3)
arr 0 0 0 = 1
arr 0 0 1 = 2
arr 0 0 2 = 3
arr 0 1 0 = 1
arr 0 1 1 = 2
arr 0 1 2 = 3
arr 1 0 0 = 4
arr 1 0 1 = 5
arr 1 0 2 = 6
arr 1 1 0 = 4
arr 1 1 1 = 5
arr 1 1 2 = 6
arr 2 0 0 = 7
arr 2 0 1 = 8
arr 2 0 2 = 9
arr 2 1 0 = 7
arr 2 1 1 = 8
arr 2 1 2 = 9


slicing

In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9])

arr[1:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[:4]

array([1, 2, 3, 4])

In [28]:
arr[1:5]

array([2, 3, 4, 5])

In [29]:
arr[1:5:2]

array([2, 4])

In [32]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr[1,1:]

array([6, 7, 8])

In [34]:
arr[2,2:4]

array([11, 12])

In [36]:
arr[0:3,1:2]

array([[ 2],
       [ 6],
       [10]])

In [35]:
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])