In [2]:
import numpy as np

search

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,1,2,3,1,2,3])

x = np.where( arr == 2)
x

(array([ 1, 15, 18], dtype=int64),)

In [4]:
x = np.where( (arr%3) == 0)
x

(array([ 2,  5,  8, 11, 16, 19], dtype=int64),)

sort

In [5]:
arr = np.array([1,2,3,1,2,3,1,2,3])
np.sort(arr)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [6]:
arr = np.array(['a','b','c','d','e','f','a','b','c','d','e','f'])
np.sort(arr)

array(['a', 'a', 'b', 'b', 'c', 'c', 'd', 'd', 'e', 'e', 'f', 'f'],
      dtype='<U1')

In [7]:
arr = np.array([[1,4,5],[4,6,2],[3,9,6]])
np.sort(arr)

array([[1, 4, 5],
       [2, 4, 6],
       [3, 6, 9]])

In [8]:
np.sort(arr,axis=0)

array([[1, 4, 2],
       [3, 6, 5],
       [4, 9, 6]])

filter

In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,])

arr[arr % 3 == 0]

array([ 3,  6,  9, 12])