In [17]:
import numpy as np

join array

In [18]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10,11,12,13,14,15,16,17,18])

ar = np.concatenate((arr, arr2))
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [19]:
arr = np.array([[1,2],[4,5]])
arr2 = np.array([[6,7],[17,18]])

ar = np.concatenate((arr, arr2),axis=1)
ar

array([[ 1,  2,  6,  7],
       [ 4,  5, 17, 18]])

In [20]:
ar = np.concatenate((arr, arr2),axis=0)
ar

array([[ 1,  2],
       [ 4,  5],
       [ 6,  7],
       [17, 18]])

In [21]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

ar = np.stack((arr, arr2))
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
ar = np.stack((arr, arr2),axis=1)
ar

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

split

In [27]:
arr = np.array([1,2,3,4,5,6])

ar = np.array_split(arr, 3)
ar

[array([1, 2]), array([3, 4]), array([5, 6])]

In [30]:
arr = np.array([1,2,3,4,5,6])

ar = np.array_split(arr, 3, axis=0)
ar

[array([1, 2]), array([3, 4]), array([5, 6])]