In [1]:
import numpy as np

shape

In [3]:
ar = np.array([[1,2,3,4],[1,2,3,4]])

print("shape", ar.shape)

shape (2, 4)


In [6]:
ar = np.array([1,2,3,4], ndmin=4)
ar

array([[[[1, 2, 3, 4]]]])

In [7]:
ar.shape

(1, 1, 1, 4)

Reshape

In [8]:
ar = np.array([1,2,3,4,5,6])

x = ar.reshape(3,2)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
x.ndim

2

In [10]:
ar = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

x = ar.reshape(2,2,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [13]:
# ar = x.reshape(1,16)
ar = x.reshape(-1)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])