numpy

In [1]:
import numpy as np

In [7]:
# rand() - generate a random value between 0    
var = np.random.rand(4)
var = np.random.rand(3,2)
var

array([[0.84425495, 0.54439065],
       [0.36139761, 0.01230595],
       [0.6158296 , 0.25268999]])

In [11]:
# randn() - generate value close to zero
arr = np.random.randn(3,2,2)
arr

array([[[ 1.32633782, -0.94320457],
        [ 1.11306315,  0.44213904]],

       [[-1.17801821,  0.08328602],
        [ 0.11023581,  0.6404231 ]],

       [[ 0.95322403,  0.26108775],
        [ 0.81483253, -0.33414567]]])

In [15]:
# randf() - [0-1)
arr = np.random.ranf(3)
arr

array([0.91087589, 0.42619065, 0.81426792])

In [24]:
# rnadint() - [a-b] 
arr = np.random.randint(4,10,5)
arr

array([5, 9, 9, 4, 8])