In [11]:
import numpy as np

shuffele

In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])

np.random.shuffle(arr)
arr

array([ 8,  9,  3, 12,  4, 11,  5,  7, 13,  1, 10,  2,  6])

unique

In [13]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,1,3,5,7,9,11,13])

x = np.unique(arr, return_index=True, return_counts=True)
x

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64),
 array([2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2], dtype=int64))

Resize

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

y = np.resize(arr,(2,3,2))
y

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

Flatten & Ravel

In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

y = np.resize(arr,(3,2))

y.flatten(order='f')


array([1, 3, 5, 2, 4, 6])

In [28]:
np.ravel(y,order='f')

array([1, 3, 5, 2, 4, 6])

In [29]:
np.ravel(y,order='a')

array([1, 2, 3, 4, 5, 6])

In [30]:
np.ravel(y,order='k')

array([1, 2, 3, 4, 5, 6])