In [12]:
import numpy as np

In [13]:
ar1 = np.array([1, 2, 3, 4])
ar2 = np.array([1])

print(ar1+ar2)

# ar2 = np.array([1,2,3])
# print(ar1+ar2)

[2 3 4 5]


In [15]:
ar2 = np.array([[1],[2],[3]])
add = ar1 + ar2
add

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [17]:
ar1 = np.array([[1],[2]])
ar2 = np.array([[1,2,3],[4,5,6]])
add = ar1 + ar2
add

array([[2, 3, 4],
       [6, 7, 8]])